apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/5 * * * *"   # runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-cron-container
              image: busybox
              args:
                - /bin/sh
                - -c
                - "echo Hello from CronJob at $(date)"
          restartPolicy: OnFailure
