name: Secure Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        sudo mv ./bin/trivy /usr/local/bin/

    - name: Install Conftest
      run: |
        wget https://github.com/open-policy-agent/conftest/releases/download/v0.41.0/conftest_0.41.0_Linux_x86_64.tar.gz
        tar -xzf conftest_0.41.0_Linux_x86_64.tar.gz
        sudo mv conftest /usr/local/bin/

    - name: Run Trivy scan
      run: trivy image nginx:latest --exit-code 1 --severity HIGH,CRITICAL

    - name: Run Conftest policy checks
      run: |
        conftest test manifests/deployment.yaml -p policies || exit 1
        conftest test manifests/cronjob.yaml -p policies || exit 1

    - name: Apply Kubernetes manifests
      run: kubectl apply -f manifests/

